# Generated by Django 5.1.4 on 2024-12-25 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0001_initial'),
        ('project', '0002_project_summary_alter_project_desc'),
        ('task', '0003_rename_parent_project_task_to_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='need',
            name='comment',
        ),
        migrations.AddField(
            model_name='need',
            name='to_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='need',
            name='to_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
    ]
