# Generated by Django 5.1.4 on 2025-01-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0002_remove_need_comment_need_to_project_need_to_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='priority',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
