# Generated by Django 5.1.4 on 2025-01-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0003_need_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='contributions',
            field=models.JSONField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
