# Generated by Django 5.1.4 on 2025-02-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0004_need_contributions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='contributions',
            field=models.JSONField(null=True),
        ),
    ]
