# Generated by Django 5.1.4 on 2025-02-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0005_alter_need_contributions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='need',
            name='contributions',
        ),
    ]
