# Generated by Django 5.1.4 on 2025-02-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0006_remove_need_contributions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='priority',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
