# Generated by Django 5.1.4 on 2025-03-17 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0007_alter_need_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='need',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='need',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='need',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated tags', null=True),
        ),
        migrations.AddField(
            model_name='need',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('members', 'Project Members Only'), ('admins', 'Admins Only')], default='public', max_length=20),
        ),
    ]
