# Generated by Django 5.1.4 on 2025-07-31 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('need', '0002_need_main_project'),
        ('project', '0005_alter_membership_is_member'),
        ('skills', '0001_initial'),
        ('task', '0003_alter_task_options_task_actual_hours_task_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, max_length=500, null=True)),
                ('desc', models.TextField()),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('solved', 'Solved'), ('unsolvable', 'Unsolvable'), ('closed', 'Closed'), ('duplicate', 'Duplicate'), ('invalid', 'Invalid'), ('in_progress', 'In Progress'), ('needs_info', 'Needs More Info'), ('reopened', 'Reopened')], default='open', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('logged_in', 'Logged-in Users Only'), ('restricted', 'Restricted Access')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, help_text='Description of how the problem was resolved', null=True)),
                ('assigned_to', models.ManyToManyField(blank=True, help_text='Users responsible for resolving this problem', related_name='assigned_problems', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_problems', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, help_text='Skills related to this problem', related_name='problems', to='skills.skill')),
                ('to_need', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='need.need')),
                ('to_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='project.project')),
                ('to_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='task.task')),
            ],
            options={
                'verbose_name_plural': 'Problems',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Problem Created'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('commented', 'Comment Added'), ('priority_changed', 'Priority Changed'), ('due_date_set', 'Due Date Set'), ('due_date_changed', 'Due Date Changed'), ('due_date_removed', 'Due Date Removed'), ('desc_changed', 'Description Changed'), ('skills_changed', 'Skills Changed'), ('resolved', 'Problem Resolved')], max_length=20)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='problems.problem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['status', 'priority'], name='problems_pr_status_bae5fe_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['created_at'], name='problems_pr_created_b0f0ea_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['due_date'], name='problems_pr_due_dat_286ced_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['visibility'], name='problems_pr_visibil_6e0155_idx'),
        ),
        migrations.AddConstraint(
            model_name='problem',
            constraint=models.CheckConstraint(condition=models.Q(('to_project__isnull', False), ('to_task__isnull', False), ('to_need__isnull', False), _connector='OR'), name='problem_must_have_relation'),
        ),
    ]
