# Generated by Django 5.1.4 on 2024-12-29 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_alter_membership_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('portal', 'Portal Administration'), ('administration', 'Administration'), ('voting', 'Voting'), ('role', 'Role'), ('auto', 'Auto')], max_length=20)),
                ('date_made', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='user.membership')),
            ],
        ),
    ]
