# Generated by Django 5.1.4 on 2025-07-28 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_membership_is_member'),
        ('skills', '0001_initial'),
        ('task', '0002_task_main_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='actual_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Actual hours spent', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Target completion date', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated hours to complete', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Under Review'), ('completed', 'Completed')], default='todo', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('logged_in', 'Logged-in Users Only'), ('restricted', 'Restricted Access')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2, null=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'priority'], name='task_task_status_38ed50_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='task_task_created_de462d_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='task_task_due_dat_c36b93_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['visibility'], name='task_task_visibil_11c254_idx'),
        ),
    ]
