# Generated by Django 5.1.4 on 2025-02-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_contributions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
