# Generated by Django 5.1.4 on 2025-07-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_name'),
        ('task', '0009_alter_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='allow_anonymous_comments',
            field=models.BooleanField(default=True, help_text='Allow non-logged-in users to comment'),
        ),
        migrations.AddField(
            model_name='task',
            name='require_comment_approval',
            field=models.BooleanField(default=False, help_text='Require comments to be approved by moderators before being visible'),
        ),
        migrations.AddField(
            model_name='task',
            name='skills',
            field=models.ManyToManyField(blank=True, to='skills.skill'),
        ),
    ]
