# Generated by Django 5.1.4 on 2024-12-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
