# Generated by Django 5.1.4 on 2025-01-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_summary_alter_project_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='collaboration_mode',
            field=models.CharField(default='volunteering', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('to_do', 'To Do'), ('doing', 'Doing'), ('done', 'Done')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated tags', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('logged_in', 'Only Logged-In Users'), ('restricted', 'Restricted (Added Users Only)'), ('private', 'Private (Author Only)')], default='public', max_length=20),
        ),
    ]
