# Generated by Django 5.1.4 on 2025-07-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_main_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_member',
            field=models.BooleanField(default=True),
        ),
    ]
