# Generated by Django 5.1.4 on 2025-07-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_membership_is_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
