# Generated by Django 5.1.4 on 2025-01-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_connection_project_connected_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributions',
            field=models.JSONField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
