# Generated by Django 5.1.4 on 2025-02-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contributions',
        ),
    ]
