# Generated by Django 5.1.4 on 2024-12-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('person', 'group')},
        ),
    ]
