# Generated by Django 5.1.4 on 2025-07-22 14:18

import imagekit.models.fields
import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=user.models.generate_avatar_upload_path),
        ),
    ]
