# Generated by Django 5.1.4 on 2025-07-26 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        ('moderation', '0001_initial'),
        ('project', '0001_initial'),
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='comment',
        #     name='to_report',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='moderation.report'),
        # ),
        migrations.AddField(
            model_name='comment',
            name='to_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task.task'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='comment',
            field=models.ForeignKey(help_text='The comment being reported', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='comment.comment'),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_reports', to='project.project'),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='reported',
            field=models.ForeignKey(blank=True, help_text='User whose comment was reported', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_against', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='reportee',
            field=models.ForeignKey(blank=True, help_text='User who filed the report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Moderator who reviewed the report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentreportgroup',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_group', to='comment.comment'),
        ),
        migrations.AddField(
            model_name='commentvote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='comment.comment'),
        ),
        migrations.AddField(
            model_name='commentvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='affected_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_impacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to='comment.comment'),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to='project.project'),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='target_report',
            field=models.ForeignKey(blank=True, help_text='Only used when scope is SINGLE_REPORT', null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.commentreport'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['status'], name='comment_com_status_c62a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='comment_com_created_a4e7bf_idx'),
        ),
        migrations.AddIndex(
            model_name='commentreport',
            index=models.Index(fields=['status'], name='comment_com_status_d10813_idx'),
        ),
        migrations.AddIndex(
            model_name='commentreport',
            index=models.Index(fields=['report_type'], name='comment_com_report__29a16f_idx'),
        ),
        migrations.AddIndex(
            model_name='commentvote',
            index=models.Index(fields=['comment', 'vote_type'], name='comment_com_comment_4f77f0_idx'),
        ),
        migrations.AddIndex(
            model_name='commentvote',
            index=models.Index(fields=['user'], name='comment_com_user_id_98bb88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together={('comment', 'user')},
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['decision'], name='comment_mod_decisio_9ffc7f_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['created_at'], name='comment_mod_created_fb8108_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['moderator'], name='comment_mod_moderat_2b3034_idx'),
        ),
    ]
