# Generated by Django 5.1.4 on 2024-12-25 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('moderation', '0001_initial'),
        ('need', '0001_initial'),
        ('project', '0002_project_summary_alter_project_desc'),
        ('task', '0002_task_parent_project_task_parent_task'),
        ('user', '0003_alter_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AddField(
            model_name='comment',
            name='to_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user.membership'),
        ),
        migrations.AddField(
            model_name='comment',
            name='to_need',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='need.need'),
        ),
        migrations.AddField(
            model_name='comment',
            name='to_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='project.project'),
        ),
        migrations.AddField(
            model_name='comment',
            name='to_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='moderation.report'),
        ),
        migrations.AddField(
            model_name='comment',
            name='to_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task.task'),
        ),
    ]
