# Generated by Django 5.1.4 on 2025-07-26 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_initial'),
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='to_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='moderation.report'),
        ),
    ]
