# Generated by Django 5.1.4 on 2025-07-31 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_commentchangelog'),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='to_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='problems.problem'),
        ),
    ]
