# Generated by Django 5.1.4 on 2024-12-29 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_rename_desc_comment_content_remove_comment_name_and_more'),
        ('decisions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='to_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='decisions.decision'),
        ),
    ]
