# Generated by Django 5.1.4 on 2025-01-11 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0012_remove_comment_to_comment_remove_comment_to_decision_and_more'),
        ('decisions', '0001_initial'),
        ('moderation', '0001_initial'),
        ('need', '0002_remove_need_comment_need_to_project_need_to_task'),
        ('task', '0003_rename_parent_project_task_to_project_and_more'),
        ('user', '0004_alter_membership_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_comments', to='comment.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='to_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='decisions.decision'),
        ),
        migrations.AddField(
            model_name='comment',
            name='to_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user.membership'),
        ),
        migrations.AddField(
            model_name='comment',
            name='to_need',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='need.need'),
        ),
        migrations.AddField(
            model_name='comment',
            name='to_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='moderation.report'),
        ),
        migrations.AddField(
            model_name='comment',
            name='to_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task.task'),
        ),
    ]
