# Generated by Django 5.1.4 on 2025-03-06 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0014_comment_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('SPAM', 'Spam or Excessive Self-Promotion'), ('SCAM', 'Scam or Fraudulent Content'), ('THEFT', 'Intellectual Property Theft'), ('HARASSMENT', 'Harassment or Bullying'), ('HATE_SPEECH', 'Hate Speech'), ('MISINFORMATION', 'Misinformation'), ('OTHER', 'Other')], default='OTHER', help_text='Type of violation being reported', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Resolved')], default='PENDING', help_text='Current status of the report', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional context provided by the reporter')),
                ('moderator_notes', models.TextField(blank=True, help_text='Notes from the moderator reviewing the report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(help_text='The comment being reported', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='comment.comment')),
                ('reported', models.ForeignKey(blank=True, help_text='User whose comment was reported', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_against', to=settings.AUTH_USER_MODEL)),
                ('reportee', models.ForeignKey(blank=True, help_text='User who filed the report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Moderator who reviewed the report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='comment_com_status_d10813_idx'), models.Index(fields=['report_type'], name='comment_com_report__29a16f_idx')],
            },
        ),
    ]
