# Generated by Django 5.1.4 on 2025-03-10 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0016_comment_author_email_comment_author_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('LIKE', 'Like'), ('LOVE', 'Love'), ('LAUGH', 'Laugh'), ('INSIGHTFUL', 'Insightful'), ('CONFUSED', 'Confused'), ('SAD', 'Sad'), ('THANKS', 'Thanks')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='comment.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment Reaction',
                'verbose_name_plural': 'Comment Reactions',
                'indexes': [models.Index(fields=['comment', 'reaction_type'], name='comment_com_comment_a4a206_idx'), models.Index(fields=['user'], name='comment_com_user_id_59761e_idx')],
                'unique_together': {('comment', 'user', 'reaction_type')},
            },
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('UPVOTE', 'Upvote'), ('DOWNVOTE', 'Downvote')], default='UPVOTE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='comment.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment Vote',
                'verbose_name_plural': 'Comment Votes',
                'indexes': [models.Index(fields=['comment', 'vote_type'], name='comment_com_comment_4f77f0_idx'), models.Index(fields=['user'], name='comment_com_user_id_98bb88_idx')],
                'unique_together': {('comment', 'user')},
            },
        ),
    ]
