# Generated by Django 5.1.4 on 2025-07-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0017_commentreaction_commentvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='reaction_type',
            field=models.CharField(choices=[('IDEA', 'Idea'), ('ISSUE', 'Issue'), ('QUESTION', 'Question'), ('PLAN', 'Plan'), ('INFO', 'Info')], max_length=20),
        ),
    ]
