# Generated by Django 5.1.4 on 2025-07-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0018_alter_commentreaction_reaction_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentReaction',
        ),
    ]
