# Generated by Django 5.1.4 on 2025-07-24 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0019_delete_commentreaction'),
        ('project', '0012_localization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reports', models.PositiveIntegerField(default=0)),
                ('report_types_summary', models.JSONField(default=dict)),
                ('first_reported_at', models.DateTimeField()),
                ('last_reported_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_group', to='comment.comment')),
            ],
            options={
                'ordering': ['-last_reported_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVE', 'Approve Comment (Dismiss Reports)'), ('HIDE', 'Hide Comment'), ('REMOVE', 'Remove Comment'), ('EDIT', 'Edit Comment Content'), ('WARN_USER', 'Warn User'), ('SUSPEND_USER', 'Suspend User'), ('BAN_USER', 'Ban User'), ('FALSE_REPORT', 'Mark as False Report')], max_length=20)),
                ('decision_scope', models.CharField(choices=[('ALL_REPORTS', 'Apply to All Reports'), ('REPORT_TYPE', 'Apply to Specific Report Type'), ('SINGLE_REPORT', 'Apply to Single Report Only')], default='ALL_REPORTS', max_length=20)),
                ('target_report_type', models.CharField(blank=True, choices=[('SPAM', 'Spam or Excessive Self-Promotion'), ('SCAM', 'Scam or Fraudulent Content'), ('THEFT', 'Intellectual Property Theft'), ('HARASSMENT', 'Harassment or Bullying'), ('HATE_SPEECH', 'Hate Speech'), ('MISINFORMATION', 'Misinformation'), ('OTHER', 'Other')], help_text='Only used when scope is REPORT_TYPE', max_length=20, null=True)),
                ('reason', models.TextField(help_text="Moderator's reason for this decision")),
                ('notify_reporters', models.BooleanField(default=True)),
                ('escalate_to_platform', models.BooleanField(default=False, help_text='Report to platform-wide moderation')),
                ('original_content', models.TextField(blank=True, null=True)),
                ('new_content', models.TextField(blank=True, null=True)),
                ('suspension_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_impacts', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to='comment.comment')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to='project.project')),
                ('target_report', models.ForeignKey(blank=True, help_text='Only used when scope is SINGLE_REPORT', null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.commentreport')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['decision'], name='comment_mod_decisio_9ffc7f_idx'), models.Index(fields=['created_at'], name='comment_mod_created_fb8108_idx'), models.Index(fields=['moderator'], name='comment_mod_moderat_2b3034_idx')],
            },
        ),
    ]
