# Generated by Django 5.1.4 on 2025-08-01 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('need', '0002_need_main_project'),
        ('plans', '0002_plan_created_by_plan_is_template_alter_step_desc_and_more'),
        ('problems', '0001_initial'),
        ('project', '0005_alter_membership_is_member'),
        ('task', '0003_alter_task_options_task_actual_hours_task_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=500)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('rejected', 'Rejected'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Status of the intro', max_length=10)),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('main_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_intros', to='project.project')),
                ('to_need', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intros', to='need.need')),
                ('to_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intros', to='plans.plan')),
                ('to_problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intros', to='problems.problem')),
                ('to_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intros', to='project.project')),
                ('to_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intros', to='task.task')),
            ],
            options={
                'verbose_name': 'Intro',
                'verbose_name_plural': 'Intros',
                'ordering': ['-created_at'],
            },
        ),
    ]
