# Generated by Django 5.1.4 on 2025-08-01 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intros', '0001_initial'),
        ('need', '0002_need_main_project'),
        ('plans', '0002_plan_created_by_plan_is_template_alter_step_desc_and_more'),
        ('problems', '0001_initial'),
        ('project', '0005_alter_membership_is_member'),
        ('task', '0003_alter_task_options_task_actual_hours_task_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intro',
            options={'ordering': ['-order', '-created_at'], 'verbose_name': 'Introduction', 'verbose_name_plural': 'Introductions'},
        ),
        migrations.AddField(
            model_name='intro',
            name='intro_type',
            field=models.CharField(choices=[('overview', 'Overview'), ('context', 'Context'), ('background', 'Background'), ('guide', 'Guide'), ('summary', 'Summary')], default='overview', help_text='Type of introduction this represents', max_length=20),
        ),
        migrations.AddField(
            model_name='intro',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (higher numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='by_user',
            field=models.ForeignKey(help_text='User who created this intro', on_delete=django.db.models.deletion.CASCADE, related_name='intros_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='intro',
            name='desc',
            field=models.TextField(help_text='Full detailed description/content'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='main_project',
            field=models.ForeignKey(blank=True, help_text='Main project context for organizational purposes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contextual_intros', to='project.project'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='name',
            field=models.CharField(help_text='Title of the introduction', max_length=200),
        ),
        migrations.AlterField(
            model_name='intro',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('rejected', 'Rejected'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Current status of this introduction', max_length=15),
        ),
        migrations.AlterField(
            model_name='intro',
            name='summary',
            field=models.CharField(help_text='Brief summary (used in listings and previews)', max_length=500),
        ),
        migrations.AlterField(
            model_name='intro',
            name='to_need',
            field=models.ForeignKey(blank=True, help_text='Need this intro relates to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intros', to='need.need'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='to_plan',
            field=models.ForeignKey(blank=True, help_text='Plan this intro relates to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intros', to='plans.plan'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='to_problem',
            field=models.ForeignKey(blank=True, help_text='Problem this intro relates to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intros', to='problems.problem'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='to_project',
            field=models.ForeignKey(blank=True, help_text='Project this intro relates to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intros', to='project.project'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='to_task',
            field=models.ForeignKey(blank=True, help_text='Task this intro relates to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intros', to='task.task'),
        ),
        migrations.AddIndex(
            model_name='intro',
            index=models.Index(fields=['status', 'created_at'], name='intros_intr_status_b1152f_idx'),
        ),
        migrations.AddIndex(
            model_name='intro',
            index=models.Index(fields=['by_user', 'status'], name='intros_intr_by_user_78b02b_idx'),
        ),
        migrations.AddIndex(
            model_name='intro',
            index=models.Index(fields=['to_project', 'status'], name='intros_intr_to_proj_e75f16_idx'),
        ),
        migrations.AddIndex(
            model_name='intro',
            index=models.Index(fields=['to_task', 'status'], name='intros_intr_to_task_098eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='intro',
            index=models.Index(fields=['main_project', 'status'], name='intros_intr_main_pr_d2d1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='intro',
            index=models.Index(fields=['order', 'created_at'], name='intros_intr_order_866520_idx'),
        ),
        migrations.AddConstraint(
            model_name='intro',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 0)), name='positive_order'),
        ),
    ]
